PRODUCTS = [
    {
        "slug": "chlorophyll-whipped-shea-butter",
        "name": "Chlorophyll Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "Deep, lasting moisture with a fresh mango-papaya finish.",
        "price": 25,
        "size": "120g",
        "badge": "Best Seller",
        "image": "photo_2_2026-06-08_18-19-49.webp",
        "description": "A soft, airy body butter whipped from unrefined shea and lightweight plant oils. Chlorophyll and mango-papaya extracts turn daily moisturising into a fresh, sensorial ritual while helping dry skin feel supple and comfortable.",
        "ingredients": ["Unrefined shea butter", "Grapeseed oil", "Coconut oil", "Olive oil", "Chlorophyll", "Mango and papaya extracts"],
        "best_for": "Dry or dull-looking skin that needs rich moisture without a waxy finish.",
        "how_to": "Warm a small amount between your palms and massage into slightly damp skin.",
    },
    {
        "slug": "pomegranate-mango-whipped-shea-butter",
        "name": "Pomegranate & Mango Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "A juicy antioxidant-rich blend for soft, radiant-looking skin.",
        "price": 25,
        "size": "120g",
        "badge": "Fruity",
        "image": "photo_8_2026-06-08_18-19-49.webp",
        "description": "This whipped shea butter combines the tropical warmth of mango with the bright character of pomegranate. The cushiony formula melts quickly, helping replenish rough areas and leaving skin smooth with a delicate fruit scent.",
        "ingredients": ["Unrefined shea butter", "Grapeseed oil", "Coconut oil", "Olive oil", "Pomegranate and mango extracts"],
        "best_for": "Normal to dry skin and anyone who enjoys a bright, fruit-led body ritual.",
        "how_to": "Massage over the body after bathing, paying extra attention to elbows, knees and heels.",
    },
    {
        "slug": "lavender-whipped-shea-butter",
        "name": "Lavender Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "Comforting moisture with a calm lavender aroma.",
        "price": 25,
        "size": "120g",
        "badge": "Night Ritual",
        "image": "photo_9_2026-06-08_18-19-49.webp",
        "description": "A deeply moisturising shea blend with a soft lavender scent made for slower evening routines. Its whipped texture spreads easily and seals in moisture without leaving skin feeling coated.",
        "ingredients": ["Unrefined shea butter", "Grapeseed oil", "Coconut oil", "Olive oil", "Lavender extract"],
        "best_for": "A soothing night-time body ritual and areas prone to dryness.",
        "how_to": "Apply before bed and massage slowly into clean skin.",
    },
    {
        "slug": "lemongrass-whipped-shea-butter",
        "name": "Lemongrass Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "Bright citrus freshness and silky everyday hydration.",
        "price": 25,
        "size": "120g",
        "badge": "Energising",
        "image": "photo_3_2026-06-05_22-40-06.webp",
        "description": "A lively lemongrass-scented body butter that pairs unrefined shea with nourishing plant oils. It softens dry skin while adding a clean, uplifting note to morning or post-shower care.",
        "ingredients": ["Unrefined shea butter", "Grapeseed oil", "Coconut oil", "Olive oil", "Lemongrass extract"],
        "best_for": "Daily body moisture and an energising start to the day.",
        "how_to": "Smooth over clean skin, concentrating on elbows, knees and other dry areas.",
    },
    {
        "slug": "grapefruit-whipped-shea-butter",
        "name": "Grapefruit Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "Crisp grapefruit scent with rich shea-based moisture.",
        "price": 25,
        "size": "120g",
        "badge": "Citrus",
        "image": "photo_5_2026-06-05_22-40-06.webp",
        "description": "A zesty body moisturiser with the rich nourishment of unrefined shea and the clean brightness of grapefruit. The whipped formula helps skin feel soft, conditioned and revived.",
        "ingredients": ["Unrefined shea butter", "Grapeseed oil", "Coconut oil", "Olive oil", "Grapefruit extract"],
        "best_for": "Dry skin and citrus lovers who want a fresh, lightweight-feeling finish.",
        "how_to": "Apply generously after showering and whenever skin needs extra comfort.",
    },
    {
        "slug": "raw-whipped-shea-butter",
        "name": "Raw Whipped Shea Butter",
        "segment": "Skin Care",
        "category": "Body Butter",
        "benefit": "Unscented, uncomplicated nourishment for face and body.",
        "price": 23,
        "size": "200g",
        "badge": "Unscented",
        "image": "photo_2_2026-06-08_18-19-49.webp",
        "description": "Pure whipped shea with no added fragrance. This versatile balm-like moisturiser melts on contact to soften dry patches and support a simple, ingredient-conscious routine.",
        "ingredients": ["100% unrefined shea butter"],
        "best_for": "Fragrance-free routines, sensitive-feeling skin and very dry areas.",
        "how_to": "Use a small amount on face or body and build as needed.",
    },
    {
        "slug": "coffee-charcoal-face-body-scrub",
        "name": "Coffee Charcoal Face & Body Scrub",
        "segment": "Skin Care",
        "category": "Exfoliator",
        "benefit": "A polishing blend for smoother, brighter-looking skin.",
        "price": 23,
        "size": "200g",
        "badge": "Weekly Ritual",
        "image": "photo_10_2026-06-08_18-19-49.webp",
        "description": "Coffee, cane sugar and activated charcoal work together to lift surface buildup while coconut and olive oils help maintain softness. The result is a satisfying polish with a warm, spa-like aroma.",
        "ingredients": ["Coffee", "Organic cane sugar", "Activated charcoal", "Coconut oil", "Olive oil", "Nutmeg", "Cinnamon"],
        "best_for": "Rough texture, dull-looking skin and a weekly body-polishing ritual.",
        "how_to": "Massage gently onto damp skin, avoiding delicate areas, then rinse well.",
    },
    {
        "slug": "activated-charcoal-cleanser",
        "name": "Activated Charcoal 3-in-1 Cleanser",
        "segment": "Skin Care",
        "category": "Cleanser",
        "benefit": "A purifying face, hair and body cleanse that respects moisture.",
        "price": 25,
        "size": "16oz",
        "badge": "Multi-use",
        "image": "photo_1_2026-06-08_18-19-49.webp",
        "description": "A flexible black-soap cleanser with activated bamboo charcoal and mineral-rich pink salt. It produces a thorough wash for face, body or scalp while avoiding the harsh, squeaky feeling of conventional detergents.",
        "ingredients": ["African black soap", "Spring water", "Activated bamboo charcoal", "Himalayan pink salt"],
        "best_for": "Combination or oily-feeling skin and anyone who prefers one versatile cleanser.",
        "how_to": "Lather a small amount in wet hands, massage gently, then rinse thoroughly.",
    },
    {
        "slug": "organic-african-black-soap",
        "name": "Organic African Black Soap",
        "segment": "African Black Soap",
        "category": "Traditional Cleanser",
        "benefit": "A handcrafted plant-based bar for face and body cleansing.",
        "price": 23,
        "size": "200g",
        "badge": "Heritage",
        "image": "photo_2026-06-09_11-04-04.webp",
        "description": "Made in the traditional style from plantain skins, cocoa pods, palm materials, charcoal and shea. This characterful bar cleanses face and body while connecting the routine to generations of West African beauty craft.",
        "ingredients": ["Plantain skins", "Cocoa pods", "Palm leaves", "Shea tree bark", "Palm oil", "Shea butter", "Charcoal"],
        "best_for": "A deep, traditional cleanse and ingredient-focused routines.",
        "how_to": "Create a lather in your hands or on a cloth; do not rub the raw bar directly on delicate facial skin.",
    },
    {
        "slug": "deep-moisturising-rosehip-oil",
        "name": "Deep Moisturising Rosehip Face & Body Oil",
        "segment": "Oil",
        "category": "Face & Body Oil",
        "benefit": "A lightweight glow oil for soft, supple-looking skin.",
        "price": 18,
        "size": "50ml",
        "badge": "Glow",
        "image": "photo_2026-06-09_09-50-19.webp",
        "description": "A silky blend of rosehip, grapeseed and jojoba oils supported by vitamins E and C. It layers easily over moisturiser or damp skin to help improve the look of dryness and uneven texture.",
        "ingredients": ["Rosehip extract", "Grapeseed oil", "Jojoba oil", "Vitamin E", "Vitamin C"],
        "best_for": "Dryness, dull-looking skin and a lightweight face-to-body glow.",
        "how_to": "Press two to four drops onto damp skin or mix into body cream.",
    },
    {
        "slug": "organic-coconut-oil",
        "name": "Organic Cold-Pressed Coconut Oil",
        "segment": "Oil",
        "category": "Multi-purpose Oil",
        "benefit": "One pure oil for soft skin, conditioned hair and scalp care.",
        "price": 23,
        "size": "200g",
        "badge": "Raw Essential",
        "image": "photo_2026-06-09_11-04-11.webp",
        "description": "Cold-pressed coconut oil kept simple and versatile. Use it as a body moisturiser, pre-shampoo treatment, scalp oil or an ingredient in your own natural-care ritual.",
        "ingredients": ["100% organic cold-pressed coconut oil"],
        "best_for": "Multi-purpose care, dry body skin and pre-wash hair treatments.",
        "how_to": "Warm between the palms before applying. Patch test before facial use.",
    },
    {
        "slug": "organic-black-seed-oil",
        "name": "Organic Cold-Pressed Black Seed Oil",
        "segment": "Oil",
        "category": "Botanical Oil",
        "benefit": "A potent Jordanian botanical oil for skin, scalp and hair.",
        "price": 25,
        "size": "50ml",
        "badge": "Cold-Pressed",
        "image": "photo_2026-06-09_09-50-19.webp",
        "description": "Cold-pressed from Nigella sativa seeds sourced from Jordan. This concentrated oil brings a rich, distinctive botanical character to scalp massage, hair treatments and targeted skin care.",
        "ingredients": ["100% organic black seed oil"],
        "best_for": "Ingredient-led rituals for scalp, hair lengths and targeted dry areas.",
        "how_to": "Use a few drops alone or blend with a lighter carrier oil.",
    },
    {
        "slug": "shea-grow-hair-scalp-oil",
        "name": "Shea-Grow Hair & Scalp Oil",
        "segment": "Hair",
        "category": "Scalp Treatment",
        "benefit": "A concentrated botanical blend for nourished roots and shine.",
        "price": 23,
        "size": "50ml",
        "badge": "Hair Ritual",
        "image": "photo_4_2026-06-05_22-40-06.webp",
        "description": "Castor, black seed, avocado and coconut oils combine with rosemary and tea tree in a rich scalp and hair treatment. It helps reduce the look of dryness and leaves lengths glossy and conditioned.",
        "ingredients": ["Castor oil", "Black seed oil", "Avocado oil", "Coconut oil", "Rosemary", "Tea tree oil"],
        "best_for": "Dry scalp, protective styles and hair that needs extra softness and shine.",
        "how_to": "Apply sparingly to the scalp or lengths and massage in. Use as a treatment or finishing oil.",
    },
    {
        "slug": "gentlemens-beard-oil",
        "name": "Gentlemen’s Beard Oil",
        "segment": "Beards",
        "category": "Beard Oil",
        "benefit": "Softens coarse facial hair and conditions the skin beneath.",
        "price": 28,
        "size": "50ml",
        "badge": "Men's Care",
        "image": "photo_2026-06-09_09-50-19.webp",
        "description": "A warm, aromatic beard oil with shea, grapeseed, castor, argan and frankincense oils. It adds natural-looking shine, improves manageability and supports a comfortable grooming routine.",
        "ingredients": ["Shea oil", "Grapeseed oil", "Castor oil", "Argan oil", "Frankincense", "Cedarwood", "Eucalyptus mint"],
        "best_for": "Dry or coarse beards and skin that feels tight beneath facial hair.",
        "how_to": "Massage three to six drops through a damp beard and into the skin.",
    },
    {
        "slug": "shea-butter-beard-balm",
        "name": "Shea Butter Beard Balm",
        "segment": "Beards",
        "category": "Beard Styling",
        "benefit": "Tames, softens and adds light shape without stiffness.",
        "price": 28,
        "size": "8oz",
        "badge": "Style & Care",
        "image": "photo_2026-06-09_11-04-16.webp",
        "description": "A conditioning styling balm made with shea butter, beeswax and plant oils. It gives beards light control, smooths flyaways and helps distribute moisture from root to tip.",
        "ingredients": ["Shea butter", "Beeswax", "Coconut oil", "Jojoba oil", "Cedarwood", "Lemongrass oil"],
        "best_for": "Medium to full beards that need softness, shine and everyday control.",
        "how_to": "Warm a small amount between fingers, work through the beard, then shape with a comb or brush.",
    },
    {
        "slug": "gentlemens-beard-wash",
        "name": "Gentlemen’s Beard Wash",
        "segment": "Men",
        "category": "Beard Cleanser",
        "benefit": "Cleanses beard and skin with African black soap.",
        "price": 23,
        "size": "100ml",
        "badge": "Daily Cleanse",
        "image": "photo_2026-06-09_09-50-13.webp",
        "description": "A beard-specific wash made with African black soap, avocado oil, tea tree and eucalyptus mint. It removes daily buildup while helping facial hair feel fresh, soft and ready for oil or balm.",
        "ingredients": ["African black soap", "Filtered water", "Avocado oil", "Tea tree oil", "Eucalyptus mint"],
        "best_for": "Daily or regular beard cleansing without using harsh shampoo.",
        "how_to": "Massage a small amount into a wet beard and skin, then rinse completely.",
    },
    {
        "slug": "gentlemens-beard-care-set",
        "name": "Gentlemen’s Complete Beard Care Set",
        "segment": "Men",
        "category": "Grooming Set",
        "benefit": "A complete cleanse, condition and style routine in one set.",
        "price": 75,
        "size": "3-piece set",
        "badge": "Gift Set",
        "image": "photo_7_2026-06-08_18-19-49.jpg",
        "description": "Three complementary beard essentials designed to work together: black soap beard wash, conditioning beard oil and shea butter beard balm. An easy introduction to a complete natural grooming ritual.",
        "ingredients": ["Beard wash", "Beard oil", "Beard balm"],
        "best_for": "Gifting, new beard routines and men who want a simple complete system.",
        "how_to": "Cleanse first, massage in beard oil while damp, then finish with balm for shape.",
    },
]

CATEGORIES = ["Skin Care", "Oil", "Men", "Hair", "Beards", "African Black Soap"]

HERO_SLIDES = [
    {
        "image": "aluye-chlorophyll-hero.webp",
        "eyebrow": "Pure moisture",
        "title": "Shea care, made beautifully modern.",
        "copy": "Discover whipped body butter centred on unrefined West African shea.",
        "label": "Shop skin care",
        "category": "Skin Care",
    },
    {
        "image": "aluye-cleanser-hero.webp",
        "eyebrow": "Deep cleansing",
        "title": "A fresh start for face, hair and body.",
        "copy": "African black soap and activated charcoal in one versatile daily cleanser.",
        "label": "Shop black soap",
        "category": "African Black Soap",
    },
    {
        "image": "aluye-beard-hero.webp",
        "eyebrow": "Gentlemen’s ritual",
        "title": "Beard care rooted in natural ingredients.",
        "copy": "Cleanse, condition and style with shea, black soap and botanical oils.",
        "label": "Shop men",
        "category": "Men",
    },
    {
        "image": "aluye-oil-hero.webp",
        "eyebrow": "Botanical oils",
        "title": "Nourishment from scalp to skin.",
        "copy": "Concentrated oils for softness, shine and thoughtful everyday care.",
        "label": "Shop oils",
        "category": "Oil",
    },
    {
        "image": "aluye-ritual-hero.webp",
        "eyebrow": "Body. Mind. Soul.",
        "title": "Turn everyday care into your ritual.",
        "copy": "Slow down with small-batch formulas made to be used and enjoyed.",
        "label": "Discover Aluyè",
        "category": "",
    },
]

INGREDIENTS = [
    {"name": "Unrefined Shea", "origin": "West Africa", "description": "A rich natural butter selected for its creamy texture and ability to help soften and protect dry-feeling skin."},
    {"name": "African Black Soap", "origin": "Traditional craft", "description": "A plant-based cleanser made from regional materials including plantain skins, cocoa pods, palm and shea."},
    {"name": "Activated Charcoal", "origin": "Bamboo-derived", "description": "A fine cleansing powder used to help lift surface impurities and absorb excess oil."},
    {"name": "Black Seed Oil", "origin": "Cold-pressed", "description": "A distinctive botanical oil used in targeted skin, scalp and hair rituals."},
]

BLOG_POSTS = [
    {
        "slug": "why-unrefined-shea-feels-different",
        "tag": "Ingredient Guide",
        "title": "Why unrefined shea feels different",
        "excerpt": "From origin and aroma to texture and colour, learn what sets raw shea apart.",
        "body": [
            "Unrefined shea butter is kept close to the form in which it is traditionally prepared. Its natural colour, nutty aroma and dense texture can vary slightly from batch to batch.",
            "Those variations are part of the ingredient’s character. Warm a little between your palms and the butter changes from firm to silky, making it easy to press into damp skin.",
            "At Aluyè Naturals, shea is more than a base ingredient. It is the thread that connects our modern formulas to West African beauty knowledge.",
        ],
    },
    {
        "slug": "layering-oils-and-butters",
        "tag": "Ritual",
        "title": "How to layer oils and butters",
        "excerpt": "A straightforward way to build lasting moisture without an overly heavy finish.",
        "body": [
            "Begin with clean, slightly damp skin. Water gives oils and butters something to seal in, which is why post-shower application often feels more comfortable.",
            "Use a few drops of oil first where you want lightweight slip. Follow with a small amount of whipped shea butter on areas that need a richer seal.",
            "The right amount is personal. Start small, add slowly and let your skin guide the ritual.",
        ],
    },
    {
        "slug": "beauty-wisdom-carried-forward",
        "tag": "Our Story",
        "title": "Beauty wisdom, carried forward",
        "excerpt": "How heritage ingredients inspire our modern approach to everyday care.",
        "body": [
            "Aluyè Naturals began with a belief that effective care does not need to feel disconnected from nature or tradition.",
            "Ingredients such as shea butter and African black soap have long histories of practical, everyday use. We present them in formats that fit modern bathrooms, shelves and routines.",
            "Our purpose is not to turn heritage into a trend. It is to honour the knowledge behind the ingredients while making the ritual accessible.",
        ],
    },
]
